install.packages("ISLR")
install.packages("tree")
install.packages("readxl")
library(ISLR)
library(tree)
library(readxl)
titanic<-read_excel("C:/Desktop/titanic.xlsx")
View(titanic)
attach(titanic)
range(Survived)
survived=ifelse(Survived=="Yes","Yes","No")
titanic=data.frame(titanic,survived)
titanic=titanic[,-7]
View(titanic)
set.seed(2)
train=sample(1:nrow(titanic),nrow(titanic)/2)
test=-train
training_data=titanic[train,]
testing_data=titanic[test,]
testing_survived=survived[test]
tree_model=tree(survived~.,training_data)
plot(tree_model)
text(tree_model,pretty=0)